apiVersion: v1
kind: Pod
metadata:
  name: nginx-v2
  namespace: lab-aug-2026
  labels:
    app: frontend
    release: stable
spec:
  containers:
  - name: nginx-v2
    image: nginx
    ports:
      - containerPort: 80
